---
# Keycloak NodePort Service for Desktop Access
# Created: 2025-12-10T17:56:47Z
# Purpose: Expose Keycloak on port 30080 (HTTP) and 30443 (HTTPS) for desktop access
#
# This service allows accessing Keycloak from any desktop on the network via:
# - http://<any-node-ip>:30080/auth
# - https://<any-node-ip>:30443/auth
#
# Example URLs:
# - http://192.168.4.63:30080/auth (masternode)
# - http://192.168.4.62:30080/auth (homelab)
# - http://192.168.4.61:30080/auth (storagenodet3500)
#
# Apply with:
# kubectl apply -f /opt/vmstation-org/diff-patches/20251210T175647Z-keycloak-nodeport-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  namespace: identity
  labels:
    app: keycloak
    component: nodeport
  annotations:
    description: "NodePort service for desktop access to Keycloak"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30443
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak
