---
# VMStation Kubernetes Cluster Inventory (Kubespray-compatible)
# This is the canonical inventory file - single source of truth for all cluster infrastructure

all:
  children:
    kube_control_plane:
      hosts:
        masternode:
          ansible_host: 192.168.4.63
          ansible_user: root
          ansible_connection: local
          ip: 192.168.4.63
          access_ip: 192.168.4.63
    
    kube_node:
      hosts:
        storagenodet3500:
          ansible_host: 192.168.4.61
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_k3s
          ip: 192.168.4.61
          access_ip: 192.168.4.61
        homelab:
          ansible_host: 192.168.4.62
          ansible_user: jashandeepjustinbains
          ansible_ssh_private_key_file: ~/.ssh/id_k3s
          ansible_become: true
          ansible_become_method: sudo
          ip: 192.168.4.62
          access_ip: 192.168.4.62
    
    etcd:
      hosts:
        masternode:
    
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    
    calico_rr:
      hosts: {}
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
